name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master  # or main, depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the appropriate Node.js version

      - name: Install dependencies
        run: |
          npm install -g @angular/cli  # Install Angular CLI globally
          npm install  # Install project dependencies

      - name: Build the Angular app
        run: ng build --prod --base-href "https://vinaygs911.github.io/portfolio/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # This is the branch you want to deploy to
          folder: dist/vinaygsmakam-me  # This is where the build files are located
