name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Ensure Node.js 18.x is being used

    - name: Install dependencies
      run: npm install --loglevel verbose  # Adding verbose logging for more details

    - name: Build Angular project
      run: npm run build -- --configuration production --base-href "https://vinaygs911.github.io/portfolio/"

    - name: Verify build output
      run: |
        if [ -d "dist/vinaygsmakam-me" ] && [ -f "dist/vinaygsmakam-me/index.html" ]; then
          echo "Build output verified."
        else
          echo "Build output verification failed."
          exit 1
        fi

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Personal access token for authorization
        branch: gh-pages  # The branch to deploy to
        folder: dist/vinaygsmakam-me  # The folder containing the build output