name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master  # or main, depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (v18.x)
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Use Node.js version 18.x

      - name: Install dependencies
        run: |
          npm install  # Install project dependencies (including Angular CLI locally)

      - name: Build the Angular app
        run: npx ng build --prod --base-href "https://vinaygs911.github.io/portfolio/"  # Using npx to avoid global install

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # This is the branch you want to deploy to
          folder: dist/vinaygsmakam-me  # This is where the build files are located
