name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Ensure Node.js 18.x is being used

    - name: Authenticate with npm
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        cat ~/.npmrc  # Debugging step to check the contents of the .npmrc file

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build --prod

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authorization
        branch: gh-pages  # The branch to deploy to
        folder: dist/vinaygsmakam-me  # The folder containing the build output