name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (v18.x)
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Ensure Node.js 18.x is being used

      - name: Install dependencies
        run: npm install  # Install dependencies from package.json (including Angular CLI)

      - name: Check if Angular CLI is installed
        run: |
          echo "Checking if Angular CLI is installed"
          npx ng version  # Check if npx can find Angular CLI

      - name: Build the Angular app
        run: npx ng build --prod --base-href "https://vinaygs911.github.io/portfolio/"  # Use npx to run Angular CLI locally

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Token for GitHub Pages deployment
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: dist/vinaygsmakam-me  # Folder containing the build output
